### ISSUE TITLE
Allow strings to be used by macros as names

### ISSUE THREAD

**Issue by saveriomiroddi** [austinsheep/demonstrate#6]
Not sure if it's by design, anyway... :slightly_smiling_face: 

RSpec (and ruspec, by extension) allow strings to be used for block names, eg:

```rust
    it "test subject" {
      assert_eq!(subject, 10);
    }
```

I think this is important for a declarative testing framework, as expressivity is crucial - using function names is instead very limiting.

My 10 bitcents :grimacing:

**Comment by austinsheep** [comment]
I think that seems very reasonable.

I went ahead and implemented that in https://github.com/austinsheep/demonstrate/commit/489d8313b7af838ceeaa4d2f22f395de56cf8df1 by using [voca_rs](https://github.com/e1r0nd/voca_rs).

Thanks for bringing it up!

**Comment by saveriomiroddi** [comment]
Wow, thanks for maintaing it :smile: I've also added this project to awesome-rust a few days ago. Excellent work!
