### ISSUE TITLE
Mix of mutable/immutable usage of `before` variables cause warning

### ISSUE THREAD

**Issue by saveriomiroddi** [austinsheep/demonstrate#7]
When a variable declared in a `before` block is used in both mutable and immutable way in different unit tests, it will cause a warning in the declaration.

Example (the code is a butchered version of an existing test suite):

```rust
demonstrate! {
  describe "CPU" {
    use super::*;

    before { let mut cpu = Cpu::new(); }

    it "initializes" {
      cpu.internal_ram.to_vec().iter().map(|&x| x as u32).sum::<u32>();
    }

    it "NOP (0x00)" {
        assert_cpu_execute(&mut cpu, &[0x00]);
    }
  }
}
```

The `cpu` variable needs to be mutable, however, it causes a warning "variable doesn't need to be mutable"

I don't know if this is inevitable or not, as it also happens to ruspec.

**Comment by austinsheep** [comment]
You'd need the immutable and mutable test cases to be in separate scopes.  You could have the mutable tests nested like this:
```rust
demonstrate! {
    describe "CPU" {
        use super::*;

        before { let cpu = Cpu::new(); }

        context "mutable" {
            before { let mut cpu = cpu; }

            it "initializes" {
                cpu.internal_ram.to_vec().iter().map(|&x| x as u32).sum::<u32>();
            }
        }

        it "NOP (0x00)" {
            assert_cpu_execute(&cpu, &[0x00]);
        }
    }
}
```

**Comment by saveriomiroddi** [comment]
> You'd need the immutable and mutable test cases to be in separate scopes. You could have the mutable tests nested like this:

I see - I guess it's inevitable, then :slightly_smiling_face:. Thanks!

**Comment by austinsheep** [comment]
No problem. Glad to see the crate being put to use!

**Comment by saveriomiroddi** [comment]
> No problem. Glad to see the crate being put to use!

I hope the project gets more traction. I think declaration-oriented testing is a significant omission in the Rust landscape, and this project is a very solid step in this direction (the other comparable projects are either unmaintained, or functionally inferior).
