### ISSUE TITLE
Do setup code blocks get re-run for every test?

### ISSUE THREAD

**Issue by drewm1980** [austinsheep/demonstrate#8]
In python, I'm used to using "fixtures" in pytest to amortize the cost of loading big blobs of test data over multiple tests.

https://docs.pytest.org/en/stable/fixture.html

A workaround in rust would be just to put all of my tests in one tests, but then the blob still can't be shared between modules or crates.

Does demonstrate avoid calling the setup functions, or does it just automated calling them at the front of each test?

Thanks!

**Comment by saveriomiroddi** [comment]
Not the maintainer, buf if I understand correctly, you need the same feature [I've just requested](https://github.com/austinsheep/demonstrate/issues/9) - the "before all" macro.

**Comment by austinsheep** [comment]
As @saveriomiroddi mentioned, currently demonstrate calls `before` blocks at the front of each test individually.

I am looking into implementing `before all`.  I am going to close this issue as it is a clone to #9
